### ISSUE TITLE
Idea: Rename "Content Models" CPT to "Content Type"

### ISSUE THREAD

**Issue by bacoords** [Automattic/create-content-model#37]
We've had a few discussions on the labels for this, but I think "Content Type" is clearer because it's closer to "Post Type" (which is what it actually is) but uses the less technical, more common term "Content". 

I think "Model" is a bit too technical. Just throwing this out for discussion

<img width="335" alt="Screenshot 2024-08-22 at 10 57 01 AM" src="https://github.com/user-attachments/assets/88fe68c8-2ee9-4fa5-a5b2-395751ede97e">

**Comment by zaguiini** [comment]
@candy02058912 mentioned privately that the "Content Model" name might be aligned with the WordPress community. So maybe it's not a bad name.
